name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ssh-key: ${{ secrets.DST }}
        branch: gh-pages
        folder: __site
